{
  "openapi": "3.0.1",
  "info": {
    "title": "BORGA",
    "description": "BORGA (BOaRd Games Application) provides access, through a web interface (hypermedia), to some of the features provided by the [Board Game Atlas](https://www.boardgameatlas.com/) website, making use of its [Web API](https://www.boardgameatlas.com/api/docs) for this purpose. For all group operations, a user token must be sent in the Authorization header using a Bearer Token. \n Authors: André Jesus, Nyckollas Brandão and André Santos.",
    "termsOfService": "http://swagger.io/terms/",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "games",
      "description": "Everything about Games"
    },
    {
      "name": "user",
      "description": "Everything about Users"
    }
  ],
  "paths": {
    "/games/popular": {
      "get": {
        "tags": [
          "games"
        ],
        "summary": "Gets the list of the most popular games.",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "popularGames": {
                    "OIXt3DmJU0": {
                      "id": "OIXt3DmJU0",
                      "name": "Catan",
                      "url": "https://www.boardgameatlas.com/game/OIXt3DmJU0/catan",
                      "image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324722072.jpg",
                      "amazon_rank": 133,
                      "price": "32.97"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/games/search": {
      "get": {
        "tags": [
          "games"
        ],
        "summary": "Searches games by name.",
        "parameters": [
          {
            "name": "gameName",
            "in": "query",
            "description": "The name of the game to search.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Limits the number of results returned. The max limit is 100. The default is 30.",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "order_by",
            "in": "query",
            "description": "Provide the name of another parameter and it will order the results according to it.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "This determines which direction the list is shown in based on the order_by parameter.",
            "required": false,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "games": [
                    {
                      "id": "OIXt3DmJU0",
                      "name": "Catan",
                      "url": "https://www.boardgameatlas.com/game/OIXt3DmJU0/catan",
                      "image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324722072.jpg",
                      "publisher": "KOSMOS",
                      "amazon_rank": 133,
                      "price": "32.97"
                    },
                    {
                      "id": "E5TYKwLTf0",
                      "name": "Catan: Cities & Knights",
                      "url": "https://www.boardgameatlas.com/game/E5TYKwLTf0/catan-cities-and-knights-expansion",
                      "image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257359245-51DYsPZcYyL.jpg",
                      "publisher": "Catan Studio",
                      "amazon_rank": 4435,
                      "price": "44.00"
                    },
                    {
                      "id": "EvYzPCnCGG",
                      "name": "Catan: 5-6 Player Extension",
                      "url": "https://www.boardgameatlas.com/game/EvYzPCnCGG/catan-56-player-extension",
                      "image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254797611-51uLrWkNt0L.jpg",
                      "publisher": "Catan Studio",
                      "amazon_rank": 534,
                      "price": "15.49"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"gameName\":\"Catan\"}",
                    "info": {
                      "gameName": "Catan"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Creates a new user.",
        "requestBody": {
          "description": "User information",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "userId": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "Created user": {
                    "userId": "12345",
                    "token": "944716df-96a8-442e-a3e6-834ac0dadde7",
                    "userName": "Paulão"
                  }
                }
              }
            }
          },
          "409": {
            "description": "already exists",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1002,
                    "name": "ALREADY_EXISTS",
                    "message": "The item already exists {\"userId\":\"A48287\"}",
                    "info": {
                      "userId": "A48287"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{userId}/groups": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Creates a group providing its name and description.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The user ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Group information",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "groupId": {
                    "type": "string"
                  },
                  "groupName": {
                    "type": "string"
                  },
                  "groupDescription": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "Created group": {
                    "groupId": "NegG",
                    "groupName": "Negotiation games",
                    "groupDescription": "This is a group of negotiation games."
                  }
                }
              }
            }
          },
          "404": {
            "description": "not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"userId\":\"A4828723\"}",
                    "info": {
                      "userId": "A4828723"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "already exists",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1002,
                    "name": "ALREADY_EXISTS",
                    "message": "The item already exists {\"groupName\":\"FPS Games\"}",
                    "info": {
                      "groupName": "FPS Games"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Lists all groups.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The user ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "NegG": {
                    "name": "Negotiation games",
                    "description": "This is a group of negotiation games.",
                    "games": {
                      "OIXt3DmJU0": "Catan"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"userId\":\"A4828723\"}",
                    "info": {
                      "userId": "A4828723"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{userId}/groups/{groupId}": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Edits a group by changing its name and description.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The user ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "groupId",
            "in": "path",
            "description": "The group ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Group information",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "groupName": {
                    "type": "string"
                  },
                  "newGroupName": {
                    "type": "string"
                  },
                  "newDescription": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "Edited group": {
                    "groupId": "NegG",
                    "newGroupName": "Negotiation and Economic Games",
                    "newGroupDescription": "This is a group of negotiation and economic games."
                  }
                }
              }
            }
          },
          "404": {
            "description": "user or group not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"userId\":\"A4828723\"}",
                    "info": {
                      "userId": "A4828723"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Deletes a group.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The user ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "groupId",
            "in": "path",
            "description": "The group ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "Deleted group": {
                    "groupId": "NegG",
                    "groupName": "Negotiation and Economic Games",
                    "groupDescription": "This is a group of negotiation and economic games."
                  }
                }
              }
            }
          },
          "404": {
            "description": "user or group not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"userId\":\"A4828723\"}",
                    "info": {
                      "userId": "A4828723"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Gets the details of a group.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The user ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "groupId",
            "in": "path",
            "description": "The group ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "name": "Negotiation games",
                  "description": "This is a group of negotiation games.",
                  "games": {}
                }
              }
            }
          },
          "404": {
            "description": "user or group not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"userId\":\"A4828723\"}",
                    "info": {
                      "userId": "A4828723"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{userId}/groups/{groupId}/games": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Adds a game to a group.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The user ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "groupId",
            "in": "path",
            "description": "The group ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Game information",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "gameId": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "Added game": {
                    "id": "OIXt3DmJU0",
                    "name": "Catan",
                    "url": "https://www.boardgameatlas.com/game/OIXt3DmJU0/catan",
                    "image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324722072.jpg",
                    "amazon_rank": 133,
                    "price": "32.97"
                  }
                }
              }
            }
          },
          "404": {
            "description": "user or group not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"userId\":\"A4828723\"}",
                    "info": {
                      "userId": "A4828723"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{userId}/groups/{groupId}/games/{gameId}": {
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Removes a game from a group.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "The user ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "groupId",
            "in": "path",
            "description": "The group ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "gameId",
            "in": "path",
            "description": "The ID of the game to remove from the group",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "Removed game": {
                    "id": "OIXt3DmJU0",
                    "name": "Catan",
                    "url": "https://www.boardgameatlas.com/game/OIXt3DmJU0/catan",
                    "image": "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324722072.jpg",
                    "amazon_rank": 133,
                    "price": "32.97"
                  }
                }
              }
            }
          },
          "404": {
            "description": "user, group or game not found",
            "content": {
              "application/json": {
                "example": {
                  "cause": {
                    "code": 1001,
                    "name": "NOT_FOUND",
                    "message": "The item does not exist {\"userId\":\"A4828723\"}",
                    "info": {
                      "userId": "A4828723"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "Game": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "publisher": {
            "type": "string"
          },
          "amazon_rank": {
            "type": "integer"
          },
          "price": {
            "type": "string"
          }
        },
        "xml": {
          "name": "Game"
        }
      },
      "Group": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "games": {
            "type": "object",
            "additionalProperties": {
              "type": "string",
              "example": {
                "gameId": "gameName"
              }
            }
          }
        },
        "xml": {
          "name": "Group"
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "groups": {
            "type": "object",
            "additionalProperties": {
              "type": "string",
              "example": {
                "groupId": "groupObj"
              }
            }
          }
        },
        "xml": {
          "name": "User"
        }
      }
    }
  }
}